### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by xAffinity** [drandreaskrueger/chainhammer#1]
Hi, can i check what python version you are using for your benchmarks? I run into many errors when installing the dependencies in the virtualenv. Failed with python3.5.2 and am currently also failing with python3.6.6 when running ./deploy.py and also the other py files

**Comment by drandreaskrueger** [comment]
Sorry to hear that. 

Yes, it is a moving target. And there were times in which there was not even a coherent state of all dependencies possible - so I started to FIX and hardcode the version numbers, to what seemed to work.

Have a look here, that is the newest (list of version numbers) that actually worked, on AWS machines:  
https://github.com/drandreaskrueger/chainhammer/blob/master/reproduce.md#chainhammer-1

-->

> these autumn versions:   

```
pip3 install --upgrade py-solc==3.1.0 web3==4.7.2 web3[tester]==4.7.2 rlp==0.6.0 eth-testrpc==1.3.5 requests==2.19.1 pandas==0.23.4 matplotlib==3.0.0
```


> python version

At the very beginning, all my tools dump all relevant versions with which they are running, see e.g. here: https://github.com/drandreaskrueger/chainhammer/blob/master/parity.md#run-17

```
./tps.py 
versions: web3 4.3.0, py-solc: 2.1.0, solc 0.4.24+commit.e67f0147.Linux.gpp, testrpc 1.3.4, python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
web3 connection established, blockNumber = 13, node version string =  Parity//v1.8.11-stable-21522ff-20180227/x86_64-linux-gnu/rustc1.24.0
```

that was a *relatively* recent run, but not yet with the newest dependencies, mentioned above. But it was using Python 3.5.3

Out of the top of my head, I do not know what the current AWS image ("AMI") contains. 

**Please just start an instance** (free tier! no costs! when choosing `t2.micro` instance) - just because **in there**, all dependencies are actually working. All readily installed, just launch the ethereum network of choice + my chainhammer tools. 

https://github.com/drandreaskrueger/chainhammer/blob/master/reproduce.md#readymade-amazon-ami

here is my newest AMI:  "chainhammer-v37"

https://eu-west-2.console.aws.amazon.com/ec2/v2/home?region=eu-west-2#Images:visibility=public-images;search=chainhammer-v37;sort=name

hope that helps

**Comment by drandreaskrueger** [comment]
never seen that error, but perhaps you can solve it:

https://www.google.co.uk/search?q=functoolz.cpython-35m-x86_64-linux-gnu.so%3A+undefined+symbol%3A+PyFPE_jbuf

**Comment by drandreaskrueger** [comment]
perhaps report that as a github issue to https://pypi.org/project/eth-account/ that they have that problem with https://pypi.org/project/cytoolz/ ?

**Comment by drandreaskrueger** [comment]
but first (a) destroy the virtualenv again, and start over with the above list of dependency versions, and if that still does not work, then (b) go for the Amazon AWS approach - it's worth it, and will save you tons of time.

**Comment by drandreaskrueger** [comment]
@xAffinity

**Comment by drandreaskrueger** [comment]
tried it on my own local (Debian) machine, it works.

Versions:
```
./tps.py 
versions: web3 4.7.2, py-solc: 3.1.0, solc 0.4.24+commit.e67f0147.Linux.gpp, testrpc 1.3.5, python 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
```

--> Python 3.5.3

perhaps this new file helps:

https://github.com/drandreaskrueger/chainhammer/blob/master/requirements.txt

**Comment by xAffinity** [comment]
@drandreaskrueger  Thank you for your advice and help. Will try to use the requirements.txt u provided to install the virtualenv ( i presume ) . If all else fails, will be using your AMIs to benchmark the blockchains.

**Comment by drandreaskrueger** [comment]
Thanks for the update, @xAffinity 

It might be as simple as

    pip3 install -r requirements.txt 

inside your python3 virtualenv. I have used the [freeze](https://www.google.co.uk/search?q=pip+requirements+freeze+install) command to generate it.

If you do use the AMI, beware that you (a) need a credit card but (b) there won't be any costs incurred as long as you are careful not to start large machines. Amazon has this "free tier" which gives you access for a year withou charging you for x hours per month of one small machine. OR many machines in parallel but only for a day, and the kill them again. As soon as you "terminate" them, they do not cause any costs (powering down is not enough).

Good luck.

I am on my way to the web3summit and devcon4, but every now and then check my inbox.

**Comment by xAffinity** [comment]
Hi @drandreaskrueger , i managed to get it to work using the requirements.txt file (finally!!!!) .

I did have an import problem with cytoolz ( maybe because i did not start on a fresh virtualenv ), but for the reference of anyone who needs to solve it, reinstalling(in the virtual env) cytoolz worked for me:
`pip3 uninstall cytoolz`
`pip3 install --no-cache-dir cytoolz` 

Another point to note is the solc version(not py-solc) installed on the machine. Having the wrong version of solc would lead to errors during compileContract when running ./deploy.py. Make sure the solc version is not on the develop branch ( 0.5.0 ). I installed solc-0.4.25 stable build and it worked!
