### ISSUE TITLE
some patched files to run it on Ubuntu 20

### ISSUE THREAD

**Issue by Mohammed-alzuharey** [drandreaskrueger/chainhammer#21]
Hello everyone 
I running 7nodes examples locally on ubuntu virtual machine .... i need to test performance using chainhammer ...

 when i run  (./tps.py)   get 
alzuharey@alzuharey-VirtualBox:~/CH/hammer$ ./tps.py get 

Dependencies unavailable. Start virtualenv first!

ant then run alzuharey@alzuharey-VirtualBox:~/CH$ scripts/install.sh docker ubuntu
compile and install geth v1.9.6
Press enter to continue
go version go1.13.8 linux/amd64
get, compile and install geth - patience please
download repo into /home/alzuharey/go

cd /home/alzuharey/go/src/github.com/ethereum/go-ethereum; git pull --ff-only

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
    git pull <remote> <branch>
package github.com/ethereum/go-ethereum: exit status 1
"install_chapter scripts/install-go.sh" command filed with exit code 0.
alzuharey@alzuharey-VirtualBox:~/CH$

 when run ./tps.py again get same error 

lzuharey@alzuharey-VirtualBox:~/CH/hammer$ ./tps.py

Dependencies unavailable. Start virtualenv first!

Any one can help me ?  thanks

**Comment by drandreaskrueger** [comment]
Thanks, I suppose you have found these manual entry points already?
https://github.com/drandreaskrueger/chainhammer#benchmarking-a-remote-node  
https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md  

I am _downloading an Ubuntu virtual machine now_ ... then I can try to find your issue.

But one thing already: You are already running your nodes network right? Then you can skip the whole docker+networkstarters installation:

    scripts/install.sh nodocker

**Comment by drandreaskrueger** [comment]
I tried it myself.

The sub-script `scripts/install-geth.sh` was actually causing zero problems. At first. In a second run, I could replicate your error. You can fix it by first _removing any existing go geth repo_:

    rm -rf $GOPATH/src/github.com/ethereum/go-ethereum

I had not encountered it, probably because I ran it on a clean machine?

Perhaps you haven't seen that WARNING? Better DO NOT RUN ALL THIS ON YOUR MAIN MACHINE as stated in several places, e.g. here: https://github.com/drandreaskrueger/chainhammer/blob/ebfd5b0052deb9e4f3c22c79c22d9da1e0210132/scripts/install.sh#L41-L44 Instead use a cloudmachine, or a guest machine in a virtualbox.

----

But when I tried all this again, I found some unrelated issue during the later 'scripts/install-virtualenv.sh', here's a quick fix.

The thing is, when I created the repo, it was working just fine. But that is quite some while ago. Now some dependencies seem to have introduced breaking changes. I had tried to minimize that hassle, by using specific versions of everything. Still, I can now see that the (huge) installation script really did NOT run through. Sorry for that, it is not your and not my fault.

----

Steps:

If there is already a geth, remove it:

    rm -rf $GOPATH/src/github.com/ethereum/go-ethereum


a vanilla ubuntu20 machine was lacking these basic packages, I am going to add them to the script later. Until then just install manually before everything else:

    sudo apt install git curl


then clone and install everything:

    mkdir drandreaskrueger; cd drandreaskrueger
    git clone https://github.com/drandreaskrueger/chainhammer
    cd chainhammer/

    scripts/install.sh docker ubuntu 

Be very attentive what is going on there. The slightest error would cause problems later, down the road. Have a look at its sourcecode, then you see each step. But if it runs through to the end, all should be good.

In case it crashes somewhere, just continue manually.

Example: pandas could suddenly not be built anymore, I fixed that temporarily with a much newer pandas, and I hope that is NOT introducing breaking changes. (pandas==1.1.2, instead of pandas==0.23.4). Do this now:

    cat scripts/install-virtualenv.sh
    source env/bin/activate
    pip3 install --upgrade py-solc==3.2.0 web3==4.8.2 web3[tester]==4.8.2 rlp==0.6.0 eth-testrpc==1.3.5 requests==2.21.0 pandas==1.1.2 matplotlib==3.0.2 pytest==4.0.2 pytest-cov==2.6.0 jupyter==1.0.0 ipykernel==5.1.0
    ipython kernel install --user --name="Python.3.py3eth"

scripts/install-initialize.sh

Actually, even a tiny bit of python code must be patched (caused by py3.8, I guess?):

    sed -i 's/time.clock/time.time/' reader/blocksDB_create.py

Now 'activate docker' - Better now logout & login, or close the terminal, and open a new terminal, because the above scripts/install.sh might have enabled docker for the the first time for this user. 

Then start a first test run:

    cd drandreaskrueger/chainhammer/
    CH_TXS=1000 CH_THREADING="sequential" ./run.sh $HOSTNAME-TestRPC testrpc

Do NOT interrupt such runs, OR afterwards manually clean the leftovers (try staring at e.g. 'ps aux').
If everything works fine, open the results HTML or MD or PNG:

    results/runs/*.html

---

And then start the "meta run" with several different networks:

export CH_MACHINE=yourChoice
./run-all_small.sh

The parity seems broken again, *sigh*, sorry.  

To fix that would probably need more time = not now, sorry. But you don't need parity, right?

.

----------  
----------  
----------  

The "lean version":

Once have understood ^ that, you can "downgrade" the whole thing, to your case where you deploy your nodes-network yourself = so you do not need docker+networkstarters. Switch them off by "nodocker":

	cd ..
	git clone https://github.com/drandreaskrueger/chainhammer chainhammer_nodocker
	cd chainhammer_nodocker

	sed -i 's/pandas==0.23.4/pandas==1.1.2/' scripts/install-virtualenv.sh
	sed -i 's/time.clock/time.time/' reader/blocksDB_create.py

	rm -rf $GOPATH/src/github.com/ethereum/go-ethereum

	scripts/install.sh nodocker ubuntu 

Please now read and work through this: https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md#cloud-connection-attempt change the localhost:8545 to whatever port your node is running on.

    CH_TXS=1000 CH_THREADING="threaded2 300" ./run.sh "myNetworkRun001"

If you cannot get it moving past the 'is_up.sh' then (do not stop it but) start e.g. geth instead, in a second terminal, by starting a network from above

    cd drandreaskrueger/chainhammer
    networks/geth-clique-start.sh 
    tail -n 10 -f logs/network.log

then after a while you will see transactions coming into the chain, and diagrams are produced.

Good luck!

**Comment by Mohammed-alzuharey** [comment]
Thanks Dr for response... of course  already running 7 nodes network right  .... but when running the all steps and which told me about it  and need to run test  
![Screenshot from 2020-09-19 11-09-35](https://user-images.githubusercontent.com/62842470/93664820-9c5be680-fa69-11ea-8a16-4aac85b1c454.png)
![Screenshot from 2020-09-19 11-11-05](https://user-images.githubusercontent.com/62842470/93664822-9d8d1380-fa69-11ea-8654-38588a3083d1.png)
![Screenshot from 2020-09-19 11-11-12](https://user-images.githubusercontent.com/62842470/93664823-9e25aa00-fa69-11ea-9448-281ebdc10836.png)


 I get error as next :  how can solve it ?

**Comment by drandreaskrueger** [comment]
Good choice, running it in a VirtualBox now.  Which version is that?  `uname -a; lsb_release -a`

! --> Forget your 7 nodes network for now. You want to first get chainhammer working, and once you got that, you swap out the network, and use yours. Otherwise you introduce possibly extra breaking changes which I cannot follow.

> how can solve it ?

I don't know. As I can only see those 22 lines of output.   There, that Python import cannot find the `requests`  module = that means that much earlier, during the installation into the virtualenv, there must have been an error message during `pip3 install requests`. Probably.

! --> remove the env folder. Rerun the `install-virtualenv.sh` command

If there is any error, then (A) stare at the error. Re-read what it says. You might actually understand what it means, and where it comes from. Possibly a step [BEFORE the](https://github.com/drandreaskrueger/chainhammer/blob/master/scripts/install.sh) install-virtualenv.sh step had already resulted in an error? If there is any error anywhere, do not continue, but fix it first.

(That way, you work from problem to problem. If you really don't know what's wrong, feel free to get back here. Then please copy the complete output. Not a screenshot of the terminal window, but the whole output, as text.  For now, I assume that you have followed all other steps that I gave you above. Do not take "shortcuts".)

! --> Moreover, I then really recommend to you to first do it all step by step, so not immediately use the `run.sh` but go through these single steps:

> Please now read and work through this: https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md#cloud-connection-attempt change the localhost:8545 to whatever port your node is running on.

Good luck!

**Comment by Mohammed-alzuharey** [comment]
Good morning Dr ...Thanks for response... I take your advice and run step by step but still have problem when run scripts/install-virtualenv.sh  get error as next :
alzuharey@alzuharey-VirtualBox:~/quorum-examples/examples/7nodes/chainhammer_nodocker$ scripts/install-virtualenv.sh

create chainhammer virtualenv

after possibly removing a whole existing env/ folder !!!

the new virtualenv will be installed below here:
/home/alzuharey/quorum-examples/examples/7nodes/chainhammer_nodocker

Think twice. Then press enter to continue

++ rm -rf env
++ python3 -m venv env
++ echo

++ set +x
+++ source env/bin/activate
++ echo

++ python3 -m pip install --upgrade pip==18.1
Collecting pip==18.1
  Using cached pip-18.1-py2.py3-none-any.whl (1.3 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-18.1
++ pip3 install wheel
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.35.1
You are using pip version 18.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
++ pip3 install --upgrade py-solc==3.2.0 web3==4.8.2 'web3[tester]==4.8.2' rlp==0.6.0 eth-testrpc==1.3.5 requests==2.21.0 pandas==1.1.2 matplotlib==3.0.2 pytest==4.0.2 pytest-cov==2.6.0 jupyter==1.0.0 ipykernel==5.1.0
Collecting py-solc==3.2.0
  Using cached https://files.pythonhosted.org/packages/47/74/d36abca3f36ccdcd04976c50f83502c870623e5beb4a4ec96c7bad4bb9e8/py_solc-3.2.0-py3-none-any.whl
Collecting web3==4.8.2
  Using cached https://files.pythonhosted.org/packages/84/7b/8dfe018c0b94a68f88d98ff39c11471ac55ffbcb22cd7ab41010c1476a75/web3-4.8.2-py3-none-any.whl
Collecting rlp==0.6.0
Collecting eth-testrpc==1.3.5
  Using cached https://files.pythonhosted.org/packages/bc/9a/8a8c90b8ed4db0afc39bc7b67b52aa8cbbc9c08bbd93f7ca92719e3493a3/eth_testrpc-1.3.5-py3-none-any.whl
Collecting requests==2.21.0
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting pandas==1.1.2
  Using cached https://files.pythonhosted.org/packages/73/d8/2385fbe41282a38869d18fbc0d8a41f8fda6af5b300125d3bd262db7f782/pandas-1.1.2-cp38-cp38-manylinux1_x86_64.whl
Collecting matplotlib==3.0.2
  Using cached https://files.pythonhosted.org/packages/89/0c/653aec68e9cfb775c4fbae8f71011206e5e7fe4d60fcf01ea1a9d3bc957f/matplotlib-3.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ov1_kg33/matplotlib/setup.py", line 170, in <module>
        msg = pkg.install_help_msg()
      File "/tmp/pip-install-ov1_kg33/matplotlib/setupext.py", line 539, in install_help_msg
        release = platform.linux_distribution()[0].lower()
    AttributeError: module 'platform' has no attribute 'linux_distribution'
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.2]
                    python: yes [3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC
                            9.3.0]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ov1_kg33/matplotlib/
You are using pip version 18.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
++ echo

++ ipython kernel install --user --name=Python.3.py3eth
scripts/install-virtualenv.sh: line 36: ipython: command not found
++ echo

++ set +x

and i tried to slove it by delete env folder and rerun scripts/install-virtualenv.sh  and using other commands such as 
pip3 install --upgrade setuptools   and pip install --upgrade setuptools --user python    but still problem ... how can fix it ?

**Comment by drandreaskrueger** [comment]
Sorry that you still have problems. 

Have you looked at each step that I described here?
https://github.com/drandreaskrueger/chainhammer/issues/21#issuecomment-692448280

---

When you encounter an error like the above, then google it - most times someone else has already solved it:
https://www.google.com/search?q=AttributeError%3A+module+%27platform%27+has+no+attribute+%27linux_distribution%27
https://stackoverflow.com/questions/58758447/how-to-fix-module-platform-has-no-attribute-linux-distribution-when-instal

---

also, your own error message already points to some facts:

It wants to not just install but BUILD the matplotlib library, and for that it is missing dependencies: freetype, png

But I would avoid that altogether, perhaps by using a more current version of matplotlib?

---

I am trying now myself.

Ubuntu 20 seems to have broken a lot of things. Just found this for example

    since Ubuntu 20 you have to use python3- prefix instead of python-

Which versions are you using?  I ask you to REALLY follow EACH step otherwise I cannot help you.  e.g. above 

    uname -a; lsb_release -a

what is the answer?

**Comment by drandreaskrueger** [comment]
I first tried the `nodocker` installation (above called 'lean', with small details added now):

```
sudo apt install git curl

cd ..
git clone https://github.com/drandreaskrueger/chainhammer chainhammer_nodocker
cd chainhammer_nodocker

sed -i 's/pandas==0.23.4/pandas==1.1.2/' scripts/install-virtualenv.sh
sed -i 's/matplotlib==3.0.2/matplotlib==3.3.2/' scripts/install-virtualenv.sh

sed -i 's/time.clock/time.time/' reader/blocksDB_create.py

rm -rf $GOPATH/src/github.com/ethereum/go-ethereum

scripts/install.sh nodocker ubuntu 
```

then I interrupted the geth installation impatiently, and instead directly went for the virtualenv whether the installation goes through

```
scripts/install-virtualenv.sh
```

and yes it does. So ... matplotlib 3.3.2 is solving it for now.

BUT: Now we might have a problem downstream, that the interface of the newer matplotlib introduced breaking changes ... but let's try.

**Comment by Mohammed-alzuharey** [comment]
Thanks Dr for response
I have  virtual machine Ubuntu 20.04  OS  and using python 3.8 version ... I looked in internet to try solve this problem but still it found .. OK I will install lean version as you did

**Comment by drandreaskrueger** [comment]
This is the full thingy. Tested on an Ubuntu20.04 cloud machine:

```
cd ~

sudo apt install git curl

git clone https://github.com/drandreaskrueger/chainhammer chainhammer
cd chainhammer

sed -i 's/python-dev/python3-dev/' scripts/install-packages.sh
sed -i 's/pandas==0.23.4/pandas==1.1.2/' scripts/install-virtualenv.sh
sed -i 's/matplotlib==3.0.2/matplotlib==3.3.2/' scripts/install-virtualenv.sh
sed -i 's/time.clock/time.time/' reader/blocksDB_create.py

# make sure that this really your go path! Must get rid of the old repo IF it existed there:
rm ~/go/src/github.com/ethereum/go-ethereum -rf 
ls ~/go/src/github.com/ethereum

scripts/install.sh docker ubuntu
```

then logout, disconnect whatever. So that docker is available for the user, for sure when you log back in.

```
cd chainhammer
source env/bin/activate
python3 --version

CH_TXS=1000 CH_THREADING="sequential" ./run.sh $HOSTNAME-TestRPC testrpc
```

Yesssssss ... that worked ...

Now you can jump up to the beginning of this issue, and walk through the steps.



Please keep me in the loop how this goes.

**Comment by drandreaskrueger** [comment]
this might help you when you have to interrupt it:

    scripts/kill-leftovers.sh 

    sudo apt install net-tools
    scripts/show-leftovers.sh

**Comment by drandreaskrueger** [comment]
### parity-deploy broken again, sorry

> Sadly, the parity-deploy tool seems to broken again, sigh, sorry.  
> To fix that would probably need more time = not now, sorry. But you don't need parity, right?  

Here's a _dirty hack_ to end the script prematurely just there, before the parity experiments even begin :
  
    git checkout -- run-all_small.sh run-all_large.sh
    sed -i "s/PARITY_VERSION=v1.11.11/set +e; trap \'\' EXIT; exit/" run-all_small.sh
    sed -i "s/PARITY_VERSION=v1.11.11/set +e; trap \'\' EXIT; exit/" run-all_large.sh

THEN you should be able to run the example experiments batch without the side effects of parity-deploy failing:

    ./run-all_small.sh

and

    ./run-all_large.sh

Oh, and mentioned everywhere, I suggest to keep a few additional terminals open, to watch the various log files, e.g.:

    tail -n 10 -f logs/network.log

**Comment by drandreaskrueger** [comment]
### results:

    chainhammer/reader/img/*.png
    chainhammer/results/runs/*.{html,md}
    chainhammer/logs/*.log

**Comment by drandreaskrueger** [comment]
Unless there are acute problems **with the above**, let's leave this like this.

Better open a new issue for your subsequent problems if you have any.
